### ISSUE TITLE
Add Hero Talent Trees

### ISSUE THREAD

**Issue by leventdeniz** [kriskate/pocket-dota#1]
[As suggested](https://www.reddit.com/r/DotA2/comments/9oi7wm/new_dota2_app/e7ulf3k) by [u/Szenphyr](https://www.reddit.com/user/Szenphyr/) hero talent trees should be added.

**Comment by kriskate** [comment]
working on it, coming up in 1.0.1 👍

**Comment by kriskate** [comment]
added in 1.1.0
