### ISSUE TITLE
Add a promt for additional downloads

### ISSUE THREAD

**Issue by leventdeniz** [kriskate/pocket-dota#4]
I don't want to download without wifi and others mitght aswell. So a promt should ask if you want to download now or not. Maybe the app should close if you choose to not download right now.

**Comment by kriskate** [comment]
great idea! it's on my to-do list as I see this as a problem as well

**Comment by kriskate** [comment]
done in 1.1.0. 

At least, partially done. If you don't do the initial download, the app cannot be accessed as it doesn't have proper data to display.
What I've done is I removed the image caching part for when there is a new wiki available.
Also, you are asked before downloading a new wiki.
